
---

- hosts: awsdb

  gather_facts: true

  become: true

  tasks:
  - name: Install nginx
    apt: pkg=nginx state=present
    become_user: root

  - name: Remove nginx default file (delete file)
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      state: touch
      mode: '666'


  - name: Insert multiple lines and Backup
    blockinfile:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      block: |
        server{
          listen 80;
            server_name development.local;
            location / {
            proxy_pass http://192.168.33.10:3000;
            }
          }
  - name: Create a symbolic link
    file:
      src: /etc/nginx/sites-enabled/reverseproxy.conf
      dest: /etc/nginx/sites-available/reverseproxy.conf
      state: link

  - name: Add env variable
    shell: export DB_HOST="mongodb://34.254.97.39:27017/posts" 

  # - name: nginx bug workaround
  #   shell: |
  #     sudo mkdir /etc/systemd/system/nginx.service.d

